### ISSUE TITLE
support reading API docs on iOS devices 

### ISSUE THREAD

**Issue by jvasileff** [ceylon/ceylon-herd#241]
The `iframe` is not scrollable on iOS. Adding these css properties fixes it:

```css
#wrap {
    -webkit-overflow-scrolling: touch;
    overflow-y: scroll;
}
```
There may be a better or more cross platform way to do this. These came from the first google search result I clicked on: https://davidwalsh.name/scroll-iframes-ios
